### ISSUE TITLE
Resolve pylint Rawhide issues

### ISSUE THREAD

**Issue by jkonecny12** [rhinstaller/pocketlint#47]
https://github.com/rhinstaller/pocketlint/runs/7281482030?check_suite_focus=true

**Comment by bcl** [comment]
I think this is resolved with pylint-2.14.4 in rawhide - https://src.fedoraproject.org/rpms/pylint/commits/rawhide

**Comment by vojtechtrefny** [comment]
The tests passed on the [0.24 release](https://github.com/rhinstaller/pocketlint/runs/7320408424?check_suite_focus=true) and I was also able to do a successful build in rawhide with `make check` enabled so I think it's safe to say the latest pylint and astroid fixed this.
